name: ci

on:
  pull_request:
    branches:
      - lambda-deployment

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: install depcheck
        run: npm install depcheck --legacy-peer-deps
      - name: Install jq
        run: sudo apt-get install jq
      - name: run depcheck
        id: rundepcheck
        run: |
          DEPCHECK=$(npx depcheck --json) || true
          echo "DEPCHECK_RESULT=$DEPCHECK" >> $GITHUB_ENV 
      - name: Process depcheck output
        id: process_depcheck_output
        run: |
          COMMENT=$(./scripts/process_depcheck_output.sh "${{ env.DEPCHECK_RESULT }}")
          echo "DEPCHECK_COMMENT=$COMMENT" >> $GITHUB_ENV
      - name: Print DEPCHECK_COMMENT
        run: echo "DEPCHECK_COMMENT=${{ env.DEPCHECK_COMMENT }}"
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ env.DEPCHECK_COMMENT }}
      