name: ci

on:
  pull_request:
    branches:
      lambda-deployment

jobs:
  depcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: install depcheck
        run: npm install depcheck --legacy-peer-deps
      - name: run depcheck 
        id: rundepcheck
        run: | 
          DEPCHECK=$(npx depcheck) 
          echo "DEPCHECK={DEPCHECK}" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            results: ${{ steps.depcheck.outputs.DEPCHECK }}